### ISSUE TITLE
Problem to compile with OSx

### ISSUE THREAD

**Issue by rateit-cool** [philjackson/js2xml#10]
I tried to install js2xml but my mac said NO WAY...

Undefined symbols for architecture x86_64:
....
ld: symbol(s) not found for architecture x86_64

I googled and find the problem at libxmljs@0.14.0 and they solved the Problem with the Version 0.14.2.
So far, ok. But the package.json of js2xml said "I need Version 0.14.0". 

So I can't install this Version.....

**Comment by matthojo** [comment]
+1

**Comment by matthojo** [comment]
#12 will fix this issue.

**Comment by philjackson** [comment]
Hopefully all fixed.
