### ISSUE TITLE
Unable to install js2xml on Windows 7 64bit

### ISSUE THREAD

**Issue by haythamnikolaidis** [philjackson/js2xml#6]
The problem seems to be with the libxmljs dependency, the version specified in the packaged.json file (0.8.1) does not build on windows, however the latest version (0.13.0) does build on windows. Upgrading the dependency does not seem to break anything as the tests compile and run fine.

**Comment by philjackson** [comment]
Thanks d3e39c4 pushed to npm should work for you now. Let me know if not.
